#!/usr/bin/env bash
#
# Copyright 2017 Cian Montgomery
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# get script dir
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR=${DIR%/} # remove trailing slashes

VE=cyst-ve

function do_init()
{
    cd $DIR
    if [ -e $VE ]; then
        echo "Virtual environment already exists, you can activate it with 'cyst-dev activate' or remove it with 'cyst-dev reset'"
        return
    fi
    echo "Creating environment."
    python3 -m virtualenv $VE
    source $VE/bin/activate
    if [ -e requirements ]; then
        python3 -m pip install -r requirements
    fi
}

function do_reset()
{
    cd $DIR
    rm -rf $VE
    echo "$VE removed."
}

function do_activate()
{
    cd $DIR
    if [ ! -e $VE ]; then
        do_init
    else
        source $VE/bin/activate
    fi
}

cmd=$1
shift

case $cmd in
"init")
  do_init
  ;;
"reset")
  do_reset
  ;;
"help")
  echo "Usage: cyst-dev init|reset|activate"
  ;;
"activate")
  do_activate
  ;;
"deactivate")
  deactivate
  ;;
*)
  echo "No command given, activating development environment."
  do_activate
  ;;
esac

